# Generated by Django 4.1.7 on 2023-03-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_streamplatform_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='streamplatform',
            table='StreamPlatform',
        ),
    ]
