# Generated by Django 4.1.7 on 2023-05-18 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0009_watchlist_avg_rating_watchlist_number_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='review',
            table='review',
        ),
        migrations.AlterModelTable(
            name='streamplatform',
            table='stream_platform',
        ),
        migrations.AlterModelTable(
            name='watchlist',
            table='watch_list',
        ),
    ]
